name: open_fashion
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4 # load fonts
  flutter_svg: ^0.22.0 # load svg image
  carousel_slider: ^4.0.0 # image slider
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0 # font awesome
  flutter_staggered_grid_view: ^0.6.2 # staggered gridview
  number_paginator: ^0.2.3 # number page
  intl_utils: ^2.8.3
  
  flutter_localizations:
    sdk: flutter
  firebase_storage: ^11.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/json/
    - lib/res/
    - lib/res/icons/
    - lib/res/images/
flutter_intl:
  enabled: true
